In [ ]:
import sklearn
import numpy as np
import pandas as pd

#Importação dos classificadores
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

#Importação de métricas e validação cruzada
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv"
# Carregar o dataset
data = pd.read_csv(url)
print(f"{len(data)} linhas lidas")
# Mostrar o dataset
data.head()

520 linhas lidas

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [ ]:
#descrição do dataset com algumas estatísticas sobre os dados
data.describe()

              Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

In [ ]:
#transforma o gênero em binário Feminino = 0 e masculino = 1
data['Gender'] = data ['Gender'].replace({'Female':0,'Male':1 })
#transforma em binário No = 0 e Yes = 1
data['Polyuria'] = data ['Polyuria'].replace({'Yes':1,'No':0 })
data['Polydipsia'] = data ['Polydipsia'].replace({'Yes':1,'No':0 })
data['sudden weight loss'] = data ['sudden weight loss'].replace({'Yes':1,'No':0 })
data['weakness'] = data ['weakness'].replace({'Yes':1,'No':0 })
data['Polyphagia'] = data ['Polyphagia'].replace({'Yes':1,'No':0 })
data['Genital thrush'] = data ['Genital thrush'].replace({'Yes':1,'No':0 })
data['visual blurring'] = data ['visual blurring'].replace({'Yes':1,'No':0 })
data['Itching'] = data ['Itching'].replace({'Yes':1,'No':0 })
data['Irritability'] = data ['Irritability'].replace({'Yes':1,'No':0 })
data['delayed healing'] = data ['delayed healing'].replace({'Yes':1,'No':0 })
data['partial paresis'] = data ['partial paresis'].replace({'Yes':1,'No':0 })
data['muscle stiffness'] = data ['muscle stiffness'].replace({'Yes':1,'No':0 })
data['Alopecia'] = data ['Alopecia'].replace({'Yes':1,'No':0 })
data['Obesity'] = data ['Obesity'].replace({'Yes':1,'No':0 })
#Positive = 1 e Negative = 0
data['class'] = data ['class'].replace({'Positive':1, 'Negative':0 })
data.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,1,0,1,0,1,0,0,0,1,0,1,0,1,1,1,1
1,58,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1
2,41,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,1
3,45,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,1
4,60,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    int64
 2   Polyuria            520 non-null    int64
 3   Polydipsia          520 non-null    int64
 4   sudden weight loss  520 non-null    int64
 5   weakness            520 non-null    int64
 6   Polyphagia          520 non-null    int64
 7   Genital thrush      520 non-null    int64
 8   visual blurring     520 non-null    int64
 9   Itching             520 non-null    int64
 10  Irritability        520 non-null    int64
 11  delayed healing     520 non-null    int64
 12  partial paresis     520 non-null    int64
 13  muscle stiffness    520 non-null    int64
 14  Alopecia            520 non-null    int64
 15  Obesity             520 non-null    int64
 16  class               520 non-null    int64
dtypes: int64(17)
memory usage: 69.2 KB

In [ ]:
#Declarando os atributos, para depois comparar como foram diagnosticados e testar eficiência do modelo
atributos = data.drop(columns = 'class')
atributos

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity
0,40,1,0,1,0,1,0,0,0,1,0,1,0,1,1,1
1,58,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0
2,41,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0
3,45,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0
4,60,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,0,1,1,1,0,1,0,0,1,0,1,1,0,0,0
516,48,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0
517,58,0,1,1,1,1,1,0,1,0,0,0,1,1,0,1
518,32,0,0,0,0,1,0,0,1,1,0,1,0,0,1,0
519,42,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
#Diagnóstico real dos pacientes
rotulos = data['class']
rotulos

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: class, Length: 520, dtype: int64

In [ ]:
#Pré processamento
from sklearn.model_selection import train_test_split
#Dividir os dados, conjunto de teste e treino
train, test, train_labels, test_labels = train_test_split(atributos, rotulos, test_size = 0.33, random_state = 42)

In [ ]:
#RFE
#Classifica os recursos mais importantes com base na eliminação recursiva.
from sklearn.feature_selection import RFE

#Essa seleção de característica utiliza uma técnica de classificação para treinar seu modelo, nesse caso foi introduzido o SVM.svc que consiste uma linha reta que seleciona os valores que chegam mais perto de sua borda.
svc = SVC(kernel="linear", C=0.025) #Padrão kernel="linear", C=1 #resultado melhor kernel="linear", C=0.025
#estimator equivale a técnica de treinamento da seleção de característica, n-features consiste no número de colunas mais importantes para o seleção de característica
#Step se do tipo inteiro corresponde ao número de recursos para remover em cada iteração e se do tipo float corresponde a porcentagem.
rfe = RFE(estimator=svc, n_features_to_select=14, step=1)
#rfe obtém os recursos de treino através do fit
rfe.fit(train, train_labels)
#X_train_rfe recebe o novo dataset após o treino da seleção de característica
X_train_rfe = rfe.transform(train)
#X_test_fsm recebe o novo dataset, com os devidos drops nas colunas com baixa relevância
X_test_rfe = rfe.transform(test)
print(type(rfe))

print(train.columns[rfe.support_])

<class 'sklearn.feature_selection._rfe.RFE'>
Index(['Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness',
       'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching',
       'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia'],
      dtype='object')

In [ ]:
#Criação de um vetor com os nomes dos Classificadores
names = ["Logistic Regression", "Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost","Naive Bayes", "QDA"]

In [ ]:
#Classificadores
classifiers = [
    LogisticRegression(random_state=42,  max_iter=500, n_jobs=-1), #(max_iter=300),
    KNeighborsClassifier(n_neighbors=1, n_jobs=-1),
    SVC(random_state=43, kernel='linear'), #kernel="linear", C=0.025
    SVC(gamma=0.01, C=100), #gamma=2, C=1 #backup gamma=0.01, C=100 #artigo gamma=0.1, C=1.7
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5, random_state=43), #max_depth=4, random_state=43
    RandomForestClassifier(max_depth=13, n_estimators=100, max_features=2, random_state=43, n_jobs=-1), #max_depth=4, n_estimators=300, max_features=2, random_state=43, n_jobs=-1
    MLPClassifier(alpha=1, max_iter=40000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

In [ ]:
# Junção do dataset para efetuar cross validation
atributos_cv = np.concatenate((X_train_rfe, X_test_rfe), axis=0)
rotulos_cv = np.concatenate((train_labels, test_labels), axis=0)

In [ ]:
#Iteração dos classificadores
for name, clf in zip(names, classifiers):
  score = cross_val_score(clf, atributos_cv, rotulos_cv, cv=10, scoring='accuracy')
  scoresf = cross_val_score(clf, atributos_cv, rotulos_cv, cv=10, scoring='f1')

  print(f'{name}')
  #print(f'Acurácia nos k-folds: {score}')
  #print(f'F1 score nos k-folds: {scoresf}')
  print('Média Acurácia: {:.4} | Desvio: {:.2}'.format(np.mean(score), np.std(score)))
  print('Média F1 Score: {:.4} | Desvio: {:.2}\n'.format(np.mean(scoresf), np.std(scoresf)))

Logistic Regression
Média Acurácia: 0.9269 | Desvio: 0.028
Média F1 Score: 0.9402 | Desvio: 0.024

Nearest Neighbors
Média Acurácia: 0.9673 | Desvio: 0.029
Média F1 Score: 0.973 | Desvio: 0.024

Linear SVM
Média Acurácia: 0.9269 | Desvio: 0.03
Média F1 Score: 0.9399 | Desvio: 0.025

RBF SVM
Média Acurácia: 0.9308 | Desvio: 0.032
Média F1 Score: 0.9427 | Desvio: 0.027

In [ ]:
# Avaliando modelo com valor curva ROC
# from sklearn.metrics import RocCurveDisplay
# import matplotlib.pyplot as plt
# Iteração dos classificadores
# for name, clf in zip(names, classifiers):
# testeroc = RocCurveDisplay.from_estimator(clf, atributos_cv, rotulos_cv)
# plt.show()